### ISSUE TITLE
bug : API Error Invalid Form Body

### ISSUE THREAD

**Issue by elliottophellia** [Eilaluth/Mocha#2]
```
4 |  * Represents an error from the Discord API.
5 |  * @extends Error
6 |  */
7 | class DiscordAPIError extends Error {
8 |   constructor(error, status, request) {
9 |     super();
        ^
DiscordAPIError: Invalid Form Body
type: This field is required
data: This field is required
application_id: This field is required
channel_id: This field is required
 path: "/interactions"
 code: "50035"

      at new DiscordAPIError (/root/mocha/node_modules/discord.js-selfbot-v13/src/rest/DiscordAPIError.js:9:4)
      at /root/mocha/node_modules/discord.js-selfbot-v13/src/rest/RequestHandler.js:401:12
      at processTicksAndRejections (:1:2602)
```

**Comment by elliottophellia** [comment]
The problem is bun runtime not the code lmao
